apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: knative-eventing.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: knative-eventing.packages.kadras.io
  releaseNotes: https://github.com/knative/eventing/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        default_broker:
          additionalProperties: false
          description: Configuration for the default in-memory broker
          properties:
            enabled:
              default: false
              description: Whether to install the default in-memory broker
              type: boolean
            namespace:
              default: default
              description: The namespace where to install the default broker
              type: string
          type: object
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: knative-eventing.packages.kadras.io
spec:
  categories:
  - eventing
  - cloudevents
  displayName: knative-eventing
  longDescription: Knative Eventing provides tools for routing events from event producers
    to sinks, enabling developers to use an event-driven architecture with their applications.
  maintainers:
  - name: Thomas Vitale
  providerName: Arktonix
  shortDescription: Toolkit to build event-driven architectures on Kubernetes.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: knative-eventing
spec:
  packageRef:
    refName: knative-eventing.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
