#@ load("@ytt:data", "data")

#@ if/end data.values.default_broker.enabled:
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: #@ data.values.default_broker.namespace
