name: Release

on:
  - workflow_dispatch

jobs:
  release:
    name: Release
    permissions:
      contents: write
      id-token: write
      packages: write
    uses: arktonix/cloud-native-utils/.github/workflows/package-release.yml@main
    with:
      package-name-slug: knative-eventing
      package-name-display: Knative Eventing
      registry-server: ghcr.io
      registry-username: ${{ github.actor }}
      image: ${{ github.repository }}
      version: 1.8.1+kadras.1
    secrets:
      pull-request-token: ${{ secrets.GH_ORG_PAT }}
