name: Test
on:
  - push

jobs:
  check-config:
    name: Check Configuration
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Carvel
        uses: vmware-tanzu/carvel-setup-action@v1.1.1
        with:
          only: ytt
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check configuration
        run: |
          make check
  test-package:
    name: Test Package
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Carvel
        uses: vmware-tanzu/carvel-setup-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run tests
        run: |
          chmod +x test/test.sh
          test/test.sh
